version: "3"

networks:
  backend:
    driver: bridge

volumes:
  code-dir:
    driver_opts:
      type: nfs
      device: /Volumes/Data/Workspace/training/docker/code
      o: bind

services:

  httpd:
    build:
      context: ./httpd/
      dockerfile: Dockerfile
    image: httpd:2.4
    container_name: httpd
    hostname: httpd
    restart: always
    networks:
      - backend
    volumes:
      - code-dir:/var/www/html
      - ./httpd/logs:/var/log/apache2
    ports:
      - "8080:80"
      - "443:443"

  mysql:
    image: "mysql:8.0.18"
    container_name: mysql
    hostname: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    ports:
      - "33061:3306"
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./code/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=654321

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    hostname: php
    restart: always
    working_dir: /var/www/html/demo
    networks:
      - backend
    volumes:
      - code-dir:/var/www/html

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: always
    ports:
      - "8888:80"
    networks: 
      - backend
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=654321


