version: "3"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  code-dir:
    driver_opts:
      type: nfs
      device: ${VOLUME_DIR}
      o: bind

services:

  httpd:
    build:
      context: ./httpd/
      dockerfile: Dockerfile
      args:
        - HTTPD_SON_VERSION=${HTTPD_VERSION}
    image: "httpd:${HTTPD_VERSION}"
    container_name: ${HTTPD_CONTAINER_NAME}
    hostname: ${HTTPD_HOSTNAME}
    restart: always
    networks:
      - backend
    volumes:
      - code-dir:${HTTPD_APP_CODE_PATH_CONTAINER}
      - ./httpd/logs:/var/log/apache2
    ports:
      - "${HTTPD_HOST_HTTP_PORT}:80"
      - "${HTTPD_HOST_HTTPS_PORT}:443"

  mysql:
    image: "mysql:${MYSQL_VERSION}"
    container_name: ${MYSQL_CONTAINER_NAME}
    hostname: ${MYSQL_HOSTNAME}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${MYSQL_DB_PATH_HOST}:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: "php-fpm:${PHP_VERSION}"
    container_name: ${PHP_CONTAINER_NAME}
    hostname: ${PHP_HOSTNAME}
    restart: always
    working_dir: ${PHP_WORKING_DIR}
    networks:
      - backend
    volumes:
      - code-dir:${PHP_APP_CODE_PATH_CONTAINER}

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:${PMA_VERSION}"
    container_name: ${PMA_CONTAINER_NAME}
    hostname: ${PMA_HOSTNAME}
    restart: always
    ports:
      - "${PMA_PORT}:80"
    networks: 
      - backend
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_HOST_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql